controllerManager:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  enableFilterNamespace: true

dashboard:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

dnsServer:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

prometheus:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"


chaosDaemon:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
