apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        target:
          type: Utilization
          averageUtilization: 75
        name: cpu
    - type: Resource
      resource:
        target:
          type: Utilization
          averageUtilization: 75
        name: memory
