grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.tibuzin.127.0.0.1.sslip.io
    tls:
      - secretName: grafana.tibuzin.127.0.0.1.sslip.io
        hosts:
          - grafana.tibuzin.127.0.0.1.sslip.io
