---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
spec:
  interval: 30m
  chart:
    spec:
      chart: chaos-mesh
      version: "2.6.3"
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
      interval: 12h
  values:
    controllerManager:
      enableFilterNamespace: true
    prometheus:
      create: true
      volume:
        storageClassName: "local-path"
