---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "6.1.7"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
