apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - ../base
  - infrastructure/letsencrypt-issuer.yaml
  - infrastructure/metallb.yaml
  - infrastructure/openebs.yaml
