---
# Source: votingapp/templates/vote-ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-ui
  name: vote-ui
spec:
  type: ClusterIP
  ports:
    - name: "vote-ui-service"
      port: 80
      targetPort: 80
  selector:
    app: vote-ui
