---
# Source: votingapp/templates/nats-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nats
  name: nats
  namespace: app
spec:
  type: ClusterIP
  ports:
    - name: "nats-service"
      port: 4222
      targetPort: 4222
  selector:
    app: nats
