---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: votingapp-selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: votingapp-cluster-issuer
spec:
  ca:
    secretName: votingapp-ca
