---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 12h
  values:
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: votingapp-cluster-issuer
        hosts:
          - grafana.meetmapper.127.0.0.1.sslip.io
        tls:
          - secretName: grafana.meetmapper.127.0.0.1.sslip.io
            hosts:
              - grafana.meetmapper.127.0.0.1.sslip.io
