apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: ''
  namespace: ''
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Parallel
      children:
        - DelayPackets
    - name: DelayPackets
      templateType: NetworkChaos
      deadline: lags the packets sent within the cluster
      networkChaos:
        action: delay
        target:
          selector:
            namespaces:
              - app
          mode: all
        selector:
          namespaces:
            - app
        mode: all
        direction: from
        delay:
          latency: 500ms
          jitter: 200ms
