apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - apps/nats.yaml
  - apps/postgresql.yaml
  - apps/result-ui.yaml
  - apps/result.yaml
  - apps/vote-ui.yaml
  - apps/vote.yaml
  - infrastructure/cert-manager.yaml
  - infrastructure/chaos-mesh.yaml
#  - infrastructure/chaos.yaml
  - infrastructure/ingress-nginx.yaml
  - infrastructure/monitoring.yaml
  - infrastructure/weave-gitops.yaml
