# k6-resource.yml

apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-flooding
  namespace: chaos
spec:
  parallelism: 4
  script:
    configMap:
      name: k6-test-config
      file: test.js
  separate: false
  runner:
    securityContext:
      runAsNonRoot: true
    resources:
      limits:
        cpu: 200m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
  starter:
    securityContext:
      runAsNonRoot: true