---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k6-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: k6-operator
      version: "3.6.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 12h
  values:
    installCRDs: true
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
