apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: votingapp-cluster-issuer
spec:
  acme:
    email: gabriel.noiret@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - http01:
          ingress:
            class: nginx
